version: '3.1'

services:

  hackerspace3:
    image: govhackau/hackerspace3
    build: .
    env_file: .env
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    restart: always
    depends_on:
      - postgres

  postgres:
    image: postgres:12.1
    env_file: .env
    volumes:
      - pg_db:/var/lib/postgresql/data
    restart: always

volumes:
  pg_db:
